# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    filter_sets: 
        medium:
            filters:
                thumbnail:
                    size: [450, 300] 
                    mode: outbound
                    alow_upscale: true
                    alow_downscale: true
        small:
            filters:
                thumbnail:
                    size: [300, 200]
                    mode: outbound
                    alow_upscale: true
                    alow_downscale: true

